name: sdkwork_knowledgebase_flutter_mobile_shell
description: SDKWork Knowledgebase Flutter mobile shell package
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sdkwork_knowledgebase_flutter_mobile_core:
    path: ../sdkwork_knowledgebase_flutter_mobile_core

dev_dependencies:
  flutter_test:
    sdk: flutter
