use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest, RateLimitTier};

const fn knowledge_route(
    method: HttpMethod,
    path: &'static str,
    operation_id: &'static str,
    permission: &'static str,
) -> HttpRoute {
    HttpRoute::dual_token(method, path, "knowledge", operation_id)
        .with_required_permission(permission)
}

const fn knowledge_abuse_route(
    method: HttpMethod,
    path: &'static str,
    operation_id: &'static str,
    permission: &'static str,
) -> HttpRoute {
    knowledge_route(method, path, operation_id, permission)
        .with_rate_limit_tier(RateLimitTier::AuthCritical)
}

const HTTP_ROUTES: &[HttpRoute] = &[
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/group_launches/consume",
        "groupLaunches.consume",
        "knowledge.spaces.read",
    )
    .with_idempotent(true),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces",
        "spaces.create",
        "knowledge.spaces.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/spaces/{spaceId}",
        "spaces.retrieve",
        "knowledge.spaces.read",
    ),
    knowledge_route(
        HttpMethod::Patch,
        "/app/v3/api/knowledge/spaces/{spaceId}",
        "spaces.update",
        "knowledge.spaces.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/spaces/{spaceId}",
        "spaces.delete",
        "knowledge.spaces.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/spaces/{spaceId}/wiki_publication",
        "wikiPublications.retrieve",
        "knowledge.spaces.read",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces/{spaceId}/wiki_publication/activate",
        "wikiPublications.activate",
        "knowledge.spaces.write",
    )
    .with_idempotent(true),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces/{spaceId}/wiki_publication/pause",
        "wikiPublications.pause",
        "knowledge.spaces.write",
    )
    .with_idempotent(true),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces/{spaceId}/wiki_source_files/{sourceFileUuid}/publish",
        "wikiSourceFiles.publish",
        "knowledge.spaces.write",
    )
    .with_idempotent(true),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces/{spaceId}/wiki_source_files/{sourceFileUuid}/unpublish",
        "wikiSourceFiles.unpublish",
        "knowledge.spaces.write",
    )
    .with_idempotent(true),
    knowledge_abuse_route(
        HttpMethod::Patch,
        "/app/v3/api/knowledge/spaces/{spaceId}/wiki_source_files/{sourceFileUuid}/visibility",
        "wikiSourceFiles.visibility.update",
        "knowledge.spaces.write",
    )
    .with_idempotent(true),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/drive_imports",
        "driveImports.create",
        "knowledge.imports.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/git_imports",
        "gitImports.create",
        "knowledge.imports.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/git_syncs",
        "gitSyncs.create",
        "knowledge.imports.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/wechat/official_accounts",
        "wechat.officialAccounts.list",
        "knowledge.wechat.manage",
    ),
    knowledge_abuse_route(
        HttpMethod::Put,
        "/app/v3/api/knowledge/wechat/official_accounts",
        "wechat.officialAccounts.update",
        "knowledge.wechat.manage",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/wechat/official_accounts/{accountId}/fan_tags",
        "wechat.officialAccounts.fanTags.list",
        "knowledge.wechat.manage",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/wechat/applets",
        "wechat.applets.list",
        "knowledge.wechat.manage",
    ),
    knowledge_abuse_route(
        HttpMethod::Put,
        "/app/v3/api/knowledge/wechat/applets",
        "wechat.applets.update",
        "knowledge.wechat.manage",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/wechat/articles/publish",
        "wechat.articles.publish",
        "knowledge.wechat.manage",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/wechat/articles/preview",
        "wechat.articles.preview",
        "knowledge.wechat.manage",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/ingests",
        "ingests.create",
        "knowledge.ingests.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/ingests/{ingestId}",
        "ingests.retrieve",
        "knowledge.ingests.read",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/documents",
        "documents.list",
        "knowledge.documents.read",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/documents",
        "documents.create",
        "knowledge.documents.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/documents/{documentId}",
        "documents.retrieve",
        "knowledge.documents.read",
    ),
    knowledge_route(
        HttpMethod::Patch,
        "/app/v3/api/knowledge/documents/{documentId}",
        "documents.update",
        "knowledge.documents.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/documents/{documentId}",
        "documents.delete",
        "knowledge.documents.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/documents/{documentId}/content",
        "documents.content.list",
        "knowledge.documents.read",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/documents/{documentId}/versions",
        "documents.versions.list",
        "knowledge.documents.read",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/documents/{documentId}/versions",
        "documents.versions.create",
        "knowledge.documents.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/concepts",
        "okf.concepts.list",
        "knowledge.okf.read",
    ),
    knowledge_route(
        HttpMethod::Put,
        "/app/v3/api/knowledge/okf/concepts/upsert",
        "okf.concepts.update",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/concepts/{conceptId}",
        "okf.concepts.retrieve",
        "knowledge.okf.read",
    ),
    knowledge_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/okf/concepts/{conceptId}",
        "okf.concepts.delete",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/concepts/{conceptId}/revisions",
        "okf.concepts.revisions.list",
        "knowledge.okf.read",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/index",
        "okf.bundle.index.list",
        "knowledge.okf.read",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/log",
        "okf.bundle.log.list",
        "knowledge.okf.read",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/profile",
        "okf.bundle.profile.list",
        "knowledge.okf.read",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/okf/queries",
        "okf.queries.create",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/okf/queries/{queryId}/file_answer",
        "okf.queries.fileAnswer",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/okf/context_packs",
        "okf.contextPacks.create",
        "knowledge.okf.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/okf/exports",
        "okf.bundle.export.create",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/okf/exports/{exportId}",
        "okf.bundle.export.retrieve",
        "knowledge.okf.read",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/okf/imports",
        "okf.bundle.import.create",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/okf/lint_runs",
        "okf.lintRuns.create",
        "knowledge.okf.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/spaces/{spaceId}/browser",
        "spaces.browser.list",
        "knowledge.spaces.read",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/retrievals",
        "retrievals.create",
        "knowledge.retrievals.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/retrievals/{retrievalId}",
        "retrievals.retrieve",
        "knowledge.retrievals.read",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/context_packs",
        "contextPacks.create",
        "knowledge.context_packs.write",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/agent_profiles",
        "agentProfiles.create",
        "knowledge.agent_profiles.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/agent_profiles/{profileId}",
        "agentProfiles.retrieve",
        "knowledge.agent_profiles.read",
    ),
    knowledge_route(
        HttpMethod::Patch,
        "/app/v3/api/knowledge/agent_profiles/{profileId}",
        "agentProfiles.update",
        "knowledge.agent_profiles.write",
    ),
    knowledge_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/agent_profiles/{profileId}",
        "agentProfiles.delete",
        "knowledge.agent_profiles.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/agent_profiles/{profileId}/bindings",
        "agentProfiles.bindings.list",
        "knowledge.agent_profiles.read",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/agent_profiles/{profileId}/bindings",
        "agentProfiles.bindings.create",
        "knowledge.agent_profiles.write",
    ),
    knowledge_route(
        HttpMethod::Patch,
        "/app/v3/api/knowledge/agent_profiles/{profileId}/bindings/{bindingId}",
        "agentProfiles.bindings.update",
        "knowledge.agent_profiles.write",
    ),
    knowledge_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/agent_profiles/{profileId}/bindings/{bindingId}",
        "agentProfiles.bindings.delete",
        "knowledge.agent_profiles.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/agent_profiles/{profileId}/retrieval_preview",
        "agentProfiles.retrievalPreview.create",
        "knowledge.agent_profiles.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/agent_profiles/{profileId}/chat",
        "agentProfiles.chat.create",
        "knowledge.agent_profiles.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/spaces/{spaceId}/context_bindings",
        "spaces.contextBindings.list",
        "knowledge.spaces.read",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces/{spaceId}/context_bindings",
        "spaces.contextBindings.create",
        "knowledge.spaces.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/spaces/{spaceId}/members",
        "spaces.members.list",
        "knowledge.spaces.read",
    ),
    knowledge_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/spaces/{spaceId}/members",
        "spaces.members.create",
        "knowledge.spaces.write",
    ),
    knowledge_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/spaces/{spaceId}/members",
        "spaces.members.delete",
        "knowledge.spaces.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/context_bindings/{bindingId}",
        "contextBindings.retrieve",
        "knowledge.context_bindings.read",
    ),
    knowledge_route(
        HttpMethod::Patch,
        "/app/v3/api/knowledge/context_bindings/{bindingId}",
        "contextBindings.update",
        "knowledge.context_bindings.write",
    ),
    knowledge_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/context_bindings/{bindingId}",
        "contextBindings.delete",
        "knowledge.context_bindings.write",
    ),
    knowledge_route(
        HttpMethod::Get,
        "/app/v3/api/knowledge/market/listings",
        "market.listings.list",
        "knowledge.market.read",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/market/subscriptions",
        "market.subscriptions.create",
        "knowledge.market.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Delete,
        "/app/v3/api/knowledge/market/subscriptions/{listingId}",
        "market.subscriptions.delete",
        "knowledge.market.write",
    ),
    knowledge_abuse_route(
        HttpMethod::Post,
        "/app/v3/api/knowledge/media_tasks",
        "mediaTasks.create",
        "knowledge.media.write",
    ),
];

pub fn app_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn group_launch_consumption_requires_framework_idempotency() {
        let manifest = app_route_manifest();
        let route = manifest
            .match_route("POST", "/app/v3/api/knowledge/group_launches/consume")
            .expect("group launch consume route");
        assert!(route.idempotent);
    }
}
