[package]
rust-version.workspace = true
name = "sdkwork-routes-knowledgebase-open-api"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-knowledgebase-contract.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-routes-knowledgebase-backend-api.workspace = true
sdkwork-knowledgebase-observability.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-web-core.workspace = true

[dev-dependencies]
tokio.workspace = true
tower.workspace = true
sdkwork-utils-rust.workspace = true
