environment = "production"

[http]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.sdkwork.com", "knowledgebase-admin.sdkwork.com", "knowledge.sdkwork.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.birdcoder.com", "knowledgebase-admin.birdcoder.com", "knowledge.birdcoder.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.dtupay.com", "knowledgebase-admin.dtupay.com", "knowledge.dtupay.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.sdkwork.cn", "knowledgebase-admin.sdkwork.cn", "knowledge.sdkwork.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.birdcoder.cn", "knowledgebase-admin.birdcoder.cn", "knowledge.birdcoder.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.dtupay.cn", "knowledgebase-admin.dtupay.cn", "knowledge.dtupay.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.skubc.com", "knowledgebase-admin.skubc.com", "knowledge.skubc.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.skubc.cn", "knowledgebase-admin.skubc.cn", "knowledge.skubc.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.zowalk.com", "knowledgebase-admin.zowalk.com", "knowledge.zowalk.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.zowalk.cn", "knowledgebase-admin.zowalk.cn", "knowledge.zowalk.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.offer86.com", "knowledgebase-admin.offer86.com", "knowledge.offer86.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.offer86.cn", "knowledgebase-admin.offer86.cn", "knowledge.offer86.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.86offer.com", "knowledgebase-admin.86offer.com", "knowledge.86offer.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["knowledgebase.86offer.cn", "knowledgebase-admin.86offer.cn", "knowledge.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

